"""Render models/<version>/metrics.json as docs/RESULTS.md (no hand-typed numbers).

Usage: python ml/report.py [--version aegis-wm-1.0.0]
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
NAMES = {
    "world_model": "**World model (ours)**",
    "xgboost_direct": "XGBoost, direct per horizon",
    "random_forest": "Random forest, direct per horizon",
    "markov_nowcast": "Markov chain on nowcast",
    "majority": "Always NORMAL",
    "persistence_oracle": "Persistence, true current state *(oracle)*",
    "markov_oracle": "Markov, true current state *(oracle)*",
}
ORDER = list(NAMES)


def f3(v):
    return "-" if v is None else f"{v:.3f}"


def pc(v, d=0):
    return "-" if v is None else f"{100 * v:.{d}f}%"


def fbeta(p, r, b):
    """F-beta from precision and recall (beta < 1 weights precision more)."""
    if p is None or r is None or (b * b * p + r) == 0:
        return None
    return (1 + b * b) * p * r / (b * b * p + r)


def fbeta_table(m: dict, b: float) -> str:
    hs = m["horizons"]
    head = "| model | " + " | ".join("now" if h == 0 else f"+{h} min" for h in hs) + " |\n|---|" + "---:|" * len(hs) + "\n"
    rows = []
    for name in ORDER:
        if name not in m["forecast"]:
            continue
        r = m["forecast"][name]
        rows.append(f"| {NAMES[name]} | " + " | ".join(
            f3(fbeta(r[str(h)]["attack_precision"], r[str(h)]["attack_recall"], b)) if str(h) in r else "-" for h in hs) + " |")
    return head + "\n".join(rows)


def table(m: dict, key: str, fmt) -> str:
    hs = m["horizons"]
    head = "| model | " + " | ".join("now" if h == 0 else f"+{h} min" for h in hs) + " |\n"
    head += "|---|" + "---:|" * len(hs) + "\n"
    rows = []
    for name in ORDER:
        if name not in m["forecast"]:
            continue
        r = m["forecast"][name]
        rows.append(f"| {NAMES[name]} | " + " | ".join(fmt(r[str(h)][key]) if str(h) in r else "-" for h in hs) + " |")
    return head + "\n".join(rows)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--version", default="aegis-wm-1.0.0")
    args = ap.parse_args()
    m = json.loads((ROOT / "models" / args.version / "metrics.json").read_text())
    manifest = json.loads((ROOT / "models" / args.version / "manifest.json").read_text())
    p = m["protocol"]
    lt = m["lead_time"]
    ew = m["early_warning"]["models"]
    out = [f"# Results - {args.version}", "",
           f"_Generated by `ml/report.py` from `models/{args.version}/metrics.json` ({m['generated_at']}). Do not edit by hand._", "",
           "## Protocol", "",
           f"- {p['type']}; {p['block_minutes']}-minute time blocks, no window shared between folds.",
           f"- {p['n_samples']:,} test samples ({p['unit']}); history {p['history']} min; Monte-Carlo samples {p['mc_samples']}.",
           "- Current-state support: " + ", ".join(f"{k} {v:,}" for k, v in p["state_support_current"].items()) + ".",
           "- Oracle rows use the TRUE current state as input. They are not deployable and are shown only as reference points.", "",
           "## Macro-F1 by horizon", "", table(m, "macro_f1", f3), "",
           "## Attack recall by horizon (any attack state predicted when one occurs)", "", table(m, "attack_recall", pc), "",
           "## Attack precision by horizon", "", table(m, "attack_precision", pc), "",
           "## Attack F-scores by horizon (binary: attack vs NORMAL at t+k)", "",
           "F0.5 weights precision (fewer false alarms), F2 weights recall (fewer missed attacks). "
           "Computed from the precision and recall above.", "",
           "### F0.5", "", fbeta_table(m, 0.5), "", "### F1", "", fbeta_table(m, 1.0), "", "### F2", "", fbeta_table(m, 2.0), "",
           "## Accuracy on minutes where the state changes (the hard part of forecasting)", "", table(m, "state_change_accuracy", pc), "",
           "## Brier score (lower is better)", "", table(m, "brier", lambda v: f"{v:.4f}"), "",
           "## World-model calibration (ECE, top-label)", "",
           "| horizon | " + " | ".join(("now" if h == 0 else f"+{h}") for h in m["horizons"]) + " |",
           "|---|" + "---:|" * len(m["horizons"]),
           "| ECE | " + " | ".join(f3(m["forecast"]["world_model"][str(h)]["ece"]) for h in m["horizons"]) + " |", "",
           f"World-model macro-F1 per fold at +1 min: {', '.join(f'{v:.3f}' for v in m['world_model_macro_f1_per_fold']['1'])}.", "",
           f"## Early warning: P(any attack within {m['early_warning']['horizon']} min)", "",
           "| model | AUROC | AUPRC | recall @thr | precision @thr | F0.5 | F1 | F2 | false-alarm rate @thr |",
           "|---|---:|---:|---:|---:|---:|---:|---:|---:|"]
    for name, r in ew.items():
        if name == "world_model_compromise_probability":
            continue
        P, R = r["precision_at_threshold"], r["recall_at_threshold"]
        out.append(f"| {NAMES.get(name, name)} | {f3(r['auroc'])} | {f3(r['auprc'])} | {pc(R)} | {pc(P)} | "
                   f"{f3(fbeta(P, R, 0.5))} | {f3(fbeta(P, R, 1))} | {f3(fbeta(P, R, 2))} | {pc(r['false_alarm_rate_at_threshold'], 1)} |")
    c = ew.get("world_model_compromise_probability")
    if c:
        out += ["", f"Compromise probability (exploitation / C2 / infiltration within the horizon): AUROC {f3(c['auroc'])}, "
                f"AUPRC {f3(c['auprc'])}, {c['positives']} positives."]
    out += ["", "Thresholds were selected on validation folds for a false-alarm rate <= 2 % on quiet host-minutes.", "",
            "## Forecast lead time", "", lt["definition"], "",
            "| onset group | n | warned before onset | mean lead | median lead when warned | detected at onset |",
            "|---|---:|---:|---:|---:|---:|"]
    groups = [("all onsets", lt["all"]), ("inside a running campaign", lt["campaign_reonset"]), ("cold onsets", lt["cold_onset"])]
    groups += [(f"&nbsp;&nbsp;{k}", v) for k, v in lt["by_state"].items()]
    for label, v in groups:
        if not v.get("n_onsets"):
            out.append(f"| {label} | 0 | - | - | - | - |")
            continue
        out.append(f"| {label} | {v['n_onsets']} | {pc(v['forecast_before_onset_rate'])} | {v['mean_lead_minutes']:.2f} min | "
                   f"{v['median_lead_minutes_when_forecast']:.0f} min | {pc(v['detected_at_onset_rate'])} |")
    out += ["", f"False warnings: {lt['false_warnings_per_host_hour']:.2f} per host-hour of quiet traffic "
            f"({lt['quiet_samples']:,} quiet host-minutes).", "",
            "## Per-state results of the world model at +1 minute", "",
            "| state | precision | recall | F0.5 | F1 | F2 | support |", "|---|---:|---:|---:|---:|---:|---:|"]
    for r in m["world_model_detail"]["1"]["per_class"]:
        out.append(f"| {r['state']} | {r['precision']:.2f} | {r['recall']:.2f} | {f3(fbeta(r['precision'], r['recall'], 0.5))} | "
                   f"{r['f1']:.2f} | {f3(fbeta(r['precision'], r['recall'], 2))} | {r['support']} |")
    out += ["", "## Permutation importance (top 10)", "", f"Target: {m['permutation_importance']['target']}.", "",
            "| feature | mean NLL increase | std over folds |", "|---|---:|---:|"]
    for r in m["permutation_importance"]["features"][:10]:
        out.append(f"| `{r['feature']}` | {r['mean_nll_increase']:.4f} | {r['std']:.4f} |")
    lat = m["inference_latency_ms_per_host"]
    out += ["", "## Production model", "",
            f"- Version `{manifest['model_version']}`, {manifest['training']['parameters']:,} parameters, "
            f"trained on folds {manifest['training'].get('train_folds')} with fold {manifest['hyperparameters']['val_fold']} for early stopping and calibration.",
            f"- Temperature {manifest['temperature']}; early-warning threshold {manifest['early_warning']['threshold']} "
            f"at horizon {manifest['early_warning']['horizon']} min.",
            f"- Weights SHA-256 `{manifest['weights_sha256']}`.",
            f"- Batched inference latency: {lat['mean']:.3f} ms per host ({lat['mc_samples']} samples, K = {lat['horizon']}).", ""]
    (ROOT / "docs" / "RESULTS.md").write_text("\n".join(out))
    print("wrote docs/RESULTS.md")
    update_readme(m)


def _replace(text: str, tag: str, body: str) -> str:
    start, end = f"<!-- {tag}:START -->", f"<!-- {tag}:END -->"
    i, j = text.index(start) + len(start), text.index(end)
    return text[:i] + "\n" + body.strip() + "\n" + text[j:]


def update_readme(m: dict) -> None:
    """Write the headline and the main results table into README.md markers."""
    wm, fc = m["forecast"]["world_model"], m["forecast"]
    ew = m["early_warning"]["models"]
    deploy = [k for k in ("xgboost_direct", "random_forest", "markov_nowcast") if k in fc]
    best5 = max(deploy, key=lambda k: fc[k]["5"]["macro_f1"])
    lt = m["lead_time"]
    def row(label, ours, base_vals):
        bname, bval = max(base_vals.items(), key=lambda kv: -1 if kv[1] is None else kv[1])
        o, b = f3(ours), f3(bval)
        if ours is not None and bval is not None:
            o, b = (f"**{o}**", b) if ours > bval else (o, f"**{b}**") if bval > ours else (o, b)
        return f"| {label} | {o} | {b} ({bname}) |"

    short = {"xgboost_direct": "XGBoost", "random_forest": "Random forest", "markov_nowcast": "Markov"}
    ewb = {short[k]: ew[k] for k in ("xgboost_direct", "markov_nowcast")}
    fb = lambda r, b: fbeta(r["precision_at_threshold"], r["recall_at_threshold"], b)  # noqa: E731
    f5 = lambda k, b: fbeta(fc[k]["5"]["attack_precision"], fc[k]["5"]["attack_recall"], b)  # noqa: E731
    wm5 = fc["world_model"]["5"]
    lines = [
        f"**Cross-validated on CIC-IDS2017** ({m['protocol']['n_samples']:,} held-out host-minutes, 5-fold blocked CV). "
        "Bold = better of the two; the baseline column shows the strongest deployable baseline for that row.", "",
        "| metric | world model (ours) | best deployable baseline |", "|---|---:|---:|",
        f"| **Early warning** (any attack within {m['early_warning']['horizon']} min), AUROC | " + row("", ew["world_model"]["auroc"], {n: r["auroc"] for n, r in ewb.items()}).split("|", 2)[2],
        "| early warning, AUPRC | " + row("", ew["world_model"]["auprc"], {n: r["auprc"] for n, r in ewb.items()}).split("|", 2)[2],
        "| early warning at the validated threshold, F0.5 | " + row("", fb(ew["world_model"], 0.5), {n: fb(r, 0.5) for n, r in ewb.items()}).split("|", 2)[2],
        "| early warning at the validated threshold, F1 | " + row("", fb(ew["world_model"], 1), {n: fb(r, 1) for n, r in ewb.items()}).split("|", 2)[2],
        "| early warning at the validated threshold, F2 | " + row("", fb(ew["world_model"], 2), {n: fb(r, 2) for n, r in ewb.items()}).split("|", 2)[2],
        "| **State 5 min ahead**, macro-F1 (7 states) | " + row("", wm5["macro_f1"], {short[k]: fc[k]["5"]["macro_f1"] for k in deploy}).split("|", 2)[2],
        "| attack 5 min ahead, precision | " + row("", wm5["attack_precision"], {short[k]: fc[k]["5"]["attack_precision"] for k in deploy}).split("|", 2)[2],
        "| attack 5 min ahead, recall | " + row("", wm5["attack_recall"], {short[k]: fc[k]["5"]["attack_recall"] for k in deploy}).split("|", 2)[2],
        "| attack 5 min ahead, F0.5 | " + row("", f5("world_model", 0.5), {short[k]: f5(k, 0.5) for k in deploy}).split("|", 2)[2],
        "| attack 5 min ahead, F2 | " + row("", f5("world_model", 2), {short[k]: f5(k, 2) for k in deploy}).split("|", 2)[2],
        "",
        "**In one line:** the world model ranks risk better (AUROC) and forecasts the future state better across all seven states "
        "(macro-F1, attack recall, F2 at +5 min), but it is less precise: precision-weighted scores (AUPRC, F0.5) and the "
        f"thresholded early-warning F-scores are equal to or slightly worse than simple baselines. {pc(lt['all']['forecast_before_onset_rate'])} of {lt['all']['n_onsets']} attack onsets were warned about "
        f"before they began, at {lt['false_warnings_per_host_hour']:.2f} false warnings per host-hour. See [Limitations](#17-limitations).",
    ]
    headline = "\n".join(lines)
    results = (table(m, "macro_f1", f3) + "\n\n*Macro-F1 by forecast horizon, pooled out-of-fold. Oracle rows are given the true current state.*"
               "\n\nFull tables (attack recall/precision, state-change accuracy, Brier, calibration, early warning, lead time, "
               "per-class, importance): [docs/RESULTS.md](docs/RESULTS.md).")
    readme = ROOT / "README.md"
    text = readme.read_text()
    text = _replace(text, "HEADLINE", headline)
    text = _replace(text, "RESULTS", results)
    readme.write_text(text)
    print("updated README.md")


if __name__ == "__main__":
    main()
