"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-28 18:48:10.543964
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_jobs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('anonymized', sa.Boolean(), nullable=False),
    sa.Column('internal_networks', sa.String(length=512), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('n_flows', sa.Integer(), nullable=True),
    sa.Column('n_hosts', sa.Integer(), nullable=True),
    sa.Column('n_windows', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('has_labels', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_jobs_created_at'), 'analysis_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_analysis_jobs_status'), 'analysis_jobs', ['status'], unique=False)
    op.create_table('audit_entries',
    sa.Column('seq', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('seq'),
    sa.UniqueConstraint('hash'),
    sa.UniqueConstraint('prev_hash')
    )
    op.create_index(op.f('ix_audit_entries_event_type'), 'audit_entries', ['event_type'], unique=False)
    op.create_table('forecasts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('context', sa.String(length=128), nullable=True),
    sa.Column('host', sa.String(length=64), nullable=True),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('horizon', sa.Integer(), nullable=False),
    sa.Column('current_state', sa.String(length=32), nullable=False),
    sa.Column('next_state', sa.String(length=32), nullable=False),
    sa.Column('attack_probability', sa.Float(), nullable=False),
    sa.Column('compromise_probability', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecasts_created_at'), 'forecasts', ['created_at'], unique=False)
    op.create_index(op.f('ix_forecasts_source'), 'forecasts', ['source'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('context', sa.String(length=128), nullable=True),
    sa.Column('host', sa.String(length=64), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('predicted_state', sa.String(length=32), nullable=False),
    sa.Column('current_state', sa.String(length=32), nullable=False),
    sa.Column('attack_probability', sa.Float(), nullable=False),
    sa.Column('compromise_probability', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('horizon', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('forecast_id', sa.String(length=32), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecasts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_context'), 'alerts', ['context'], unique=False)
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_level'), 'alerts', ['level'], unique=False)
    op.create_index(op.f('ix_alerts_source'), 'alerts', ['source'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_table('traffic_windows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('host', sa.String(length=64), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.Column('label_state', sa.String(length=32), nullable=True),
    sa.Column('current_state', sa.String(length=32), nullable=False),
    sa.Column('current_probability', sa.Float(), nullable=False),
    sa.Column('next_state', sa.String(length=32), nullable=False),
    sa.Column('next_probability', sa.Float(), nullable=False),
    sa.Column('attack_probability', sa.Float(), nullable=False),
    sa.Column('compromise_probability', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('warning', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['analysis_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traffic_windows_job_id'), 'traffic_windows', ['job_id'], unique=False)
    op.create_index('ix_windows_job_host_time', 'traffic_windows', ['job_id', 'host', 'window_start'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_windows_job_host_time', table_name='traffic_windows')
    op.drop_index(op.f('ix_traffic_windows_job_id'), table_name='traffic_windows')
    op.drop_table('traffic_windows')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_source'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_level'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_context'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_forecasts_source'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_created_at'), table_name='forecasts')
    op.drop_table('forecasts')
    op.drop_index(op.f('ix_audit_entries_event_type'), table_name='audit_entries')
    op.drop_table('audit_entries')
    op.drop_index(op.f('ix_analysis_jobs_status'), table_name='analysis_jobs')
    op.drop_index(op.f('ix_analysis_jobs_created_at'), table_name='analysis_jobs')
    op.drop_table('analysis_jobs')
    # ### end Alembic commands ###
